20-Aug-2022 11:35:30.510 SEVERE [localhost-startStop-3] org.apache.catalina.core.ApplicationContext.log Servlet pool threw unload() exception
 javax.servlet.ServletException: Servlet.destroy() for servlet pool threw exception
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1455)
	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1764)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:237)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5407)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:237)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1420)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at zaberp.zab.JDBCpool.emptyPool(JDBCpool.java:59)
	at zaberp.zab.Pool.destroy(Pool.java:31)
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1433)
	... 10 more

20-Aug-2022 11:43:14.185 SEVERE [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Servlet pool threw unload() exception
 javax.servlet.ServletException: Servlet.destroy() for servlet pool threw exception
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1455)
	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1764)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:237)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5407)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:237)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1420)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at zaberp.zab.JDBCpool.emptyPool(JDBCpool.java:59)
	at zaberp.zab.Pool.destroy(Pool.java:31)
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1433)
	... 10 more

20-Aug-2022 11:54:10.055 SEVERE [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Servlet pool threw unload() exception
 javax.servlet.ServletException: Servlet.destroy() for servlet pool threw exception
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1455)
	at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1764)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:237)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5407)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:237)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1420)
	at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at zaberp.zab.JDBCpool.emptyPool(JDBCpool.java:59)
	at zaberp.zab.Pool.destroy(Pool.java:31)
	at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1433)
	... 10 more

20-Aug-2022 15:26:19.800 SEVERE [http-nio-8090-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [gethelp] in context with path [/zab] threw exception
 java.lang.ArrayIndexOutOfBoundsException: 0
	at zaberp.zab.getHelp.doGet(getHelp.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1080)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:75)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:757)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

20-Aug-2022 15:26:19.938 SEVERE [http-nio-8090-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [gethelp] in context with path [/zab] threw exception
 java.lang.ArrayIndexOutOfBoundsException: 0
	at zaberp.zab.getHelp.doGet(getHelp.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:184)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:105)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:361)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1080)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:75)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:757)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

